spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan6
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
  spring:
    main:
      allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
  file:
    name: logs/application.log

  spring:
  main:
    allow-circular-references: true

server:
  port: 8000